# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Cedricziel"
license = "MIT"
licenselink = "https://github.com/cedricziel/hugo-blog-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/cedricziel/hugo-blog-theme"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Cedric Ziel"
  homepage = "https://blog.cedric-ziel.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
